version: '3.8'

services:
  optimism-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optimism-init
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./.env:/app/.env:ro
    ports:
      - "8545:8545"  # L2 RPC
      - "8546:8546"  # L2 WS
      - "9545:9545"  # Sequencer RPC
      - "7545:7545"  # Batcher RPC
      - "8551:8551"  # Engine API
    networks:
      - optimism-net
    env_file:
      - ./.env
    labels:
      promtail_logging: "true"
      scrape_location: "optimism"     
      instance: "optimism-init"   
      network: "optimism-net"         
      client_name: "${ROLLUP_NAME}"   
      group: "rollups"                
      host_type: "production"     
      rollup_id: "${ROLLUP_ID}"    
networks:
  optimism-net:
    driver: bridge